spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
springdoc:
  packages-to-scan: com.github.springtemplate.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method

secret-key-source: ${SECRET-KEY-SOURCE}